/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.schumager.mypassword.view;

import com.schumager.mypassword.model.DatosDelRegistro;
import com.schumager.mypassword.model.JRobot;
import com.schumager.mypassword.model.Registro;
import com.schumager.mypassword.model.util.DatosDelRegistroInput;
import com.schumager.mypassword.model.util.DatosDelRegistroOutput;
import com.schumager.mypassword.model.util.EjecutarBoot;
import com.schumager.mypassword.model.util.Util;
import com.schumager.mypassword.view.components.TextFieldLabel;
import com.schumager.mypassword.view.table.TableRegistro;
import java.awt.AWTException;
import java.awt.CardLayout;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Schumager
 */
public class PanelRegistro2 extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistro
     */
    public PanelRegistro2() {
        initComponents();
        registro = new Registro();
        panelInicio2.addAbrirActionPerformed((e)->{
            abrirActionPerformed(e);
        });
        
        panelInicio2.addNuevoActionPerformed((e)->{
            nuevoActionPerformed(e);
        });
        disable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        toolbar = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        textFieldUrl = new com.schumager.mypassword.view.components.TextFieldLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        buttonAbrir = new javax.swing.JButton();
        buttonGuardar = new javax.swing.JButton();
        buttonInicio = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jPanel2 = new javax.swing.JPanel();
        buttonInsertar = new javax.swing.JButton();
        buttonEjecutar = new javax.swing.JButton();
        panelNumeros1 = new com.schumager.mypassword.view.PanelNumeros();
        panelDeTextFields = new javax.swing.JPanel();
        textFieldNombre = new com.schumager.mypassword.view.components.TextFieldLabel();
        textFieldRecuperar = new com.schumager.mypassword.view.components.TextFieldLabel();
        textFieldMail = new com.schumager.mypassword.view.components.TextFieldLabel();
        textFieldUser = new com.schumager.mypassword.view.components.TextFieldLabel();
        textFieldPassword = new com.schumager.mypassword.view.components.TextFieldLabel();
        panelDeToggleButton = new javax.swing.JPanel();
        toggleButtonPassword = new javax.swing.JToggleButton();
        toggleButtonMail = new javax.swing.JToggleButton();
        toggleButtonEnter = new javax.swing.JToggleButton();
        toggleButtonUser = new javax.swing.JToggleButton();
        toggleButtonEnter2 = new javax.swing.JToggleButton();
        toggleButtonTab = new javax.swing.JToggleButton();
        toggleButtonBrowser = new javax.swing.JToggleButton();
        buttonLimpiar = new javax.swing.JButton();
        panelCenter = new javax.swing.JPanel();
        panelInicio2 = new com.schumager.mypassword.view.PanelInicio();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegistro = new com.schumager.mypassword.view.table.TableRegistro();
        jPanel3 = new javax.swing.JPanel();
        buttonFacebook = new javax.swing.JButton();
        buttonGoogle = new javax.swing.JButton();
        buttonTwiter = new javax.swing.JButton();
        buttonTuCuate = new javax.swing.JButton();
        buttonBrowser = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        toolbar.setRollover(true);
        toolbar.setMinimumSize(new java.awt.Dimension(201, 40));
        toolbar.setPreferredSize(new java.awt.Dimension(418, 50));
        toolbar.add(jSeparator1);

        textFieldUrl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direccio o url de la pagina para Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        textFieldUrl.setCantidad(1000);
        textFieldUrl.setPreferredSize(new java.awt.Dimension(260, 35));
        textFieldUrl.setTextLabel("Ir");
        textFieldUrl.setTitle("Inserte direccion de la pagina de login");
        toolbar.add(textFieldUrl);
        toolbar.add(jSeparator3);

        buttonAbrir.setText("Abrir");
        buttonAbrir.setFocusable(false);
        buttonAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbrirActionPerformed(evt);
            }
        });
        toolbar.add(buttonAbrir);

        buttonGuardar.setText("Guardar");
        buttonGuardar.setFocusable(false);
        buttonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });
        toolbar.add(buttonGuardar);

        buttonInicio.setText("Inicio");
        buttonInicio.setFocusable(false);
        buttonInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInicioActionPerformed(evt);
            }
        });
        toolbar.add(buttonInicio);
        toolbar.add(jSeparator2);

        add(toolbar, java.awt.BorderLayout.NORTH);

        buttonInsertar.setText("Insertar");
        buttonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertarActionPerformed(evt);
            }
        });

        buttonEjecutar.setText("Ejecutar");
        buttonEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEjecutarActionPerformed(evt);
            }
        });

        panelDeTextFields.setLayout(new javax.swing.BoxLayout(panelDeTextFields, javax.swing.BoxLayout.Y_AXIS));

        textFieldNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre de la pagina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        textFieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textFieldNombre.setTextLabel("Copy");
        textFieldNombre.setTipoDeCaracteres(3);
        textFieldNombre.setTitle("Nombre de la Pagina");
        panelDeTextFields.add(textFieldNombre);

        textFieldRecuperar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Correo o numero de recuperar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        textFieldRecuperar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textFieldRecuperar.setTextLabel("Copy");
        textFieldRecuperar.setTitle("Correo y/o numero de recuperar");
        panelDeTextFields.add(textFieldRecuperar);

        textFieldMail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Correo Electronico numero de telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        textFieldMail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textFieldMail.setTextLabel("Copy");
        textFieldMail.setTitle("Correo Electronico o numero de telefono");
        panelDeTextFields.add(textFieldMail);

        textFieldUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        textFieldUser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textFieldUser.setTextLabel("Copy");
        textFieldUser.setTitle("Insertar Usuario");
        panelDeTextFields.add(textFieldUser);

        textFieldPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        textFieldPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textFieldPassword.setTextLabel("Copy");
        textFieldPassword.setTipoDeCaracteres(4);
        textFieldPassword.setTitle("Inserte Contraseña");
        panelDeTextFields.add(textFieldPassword);

        panelDeToggleButton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Obciones que se ejecutaran", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N

        toggleButtonPassword.setText("Contraseña >");
        toggleButtonPassword.setMargin(new java.awt.Insets(2, 5, 3, 5));

        toggleButtonMail.setText("Correo >");
        toggleButtonMail.setMargin(new java.awt.Insets(2, 5, 3, 5));
        toggleButtonMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonMailActionPerformed(evt);
            }
        });

        toggleButtonEnter.setText("Enter >");
        toggleButtonEnter.setMargin(new java.awt.Insets(2, 5, 3, 5));

        toggleButtonUser.setText("Usuario >");
        toggleButtonUser.setMargin(new java.awt.Insets(2, 5, 3, 5));
        toggleButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonUserActionPerformed(evt);
            }
        });

        toggleButtonEnter2.setText("Enter >");
        toggleButtonEnter2.setMargin(new java.awt.Insets(2, 5, 3, 5));

        toggleButtonTab.setText("Tab >");
        toggleButtonTab.setMargin(new java.awt.Insets(2, 5, 3, 5));

        toggleButtonBrowser.setText("Navegador >");
        toggleButtonBrowser.setMargin(new java.awt.Insets(2, 5, 3, 5));
        toggleButtonBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonBrowserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeToggleButtonLayout = new javax.swing.GroupLayout(panelDeToggleButton);
        panelDeToggleButton.setLayout(panelDeToggleButtonLayout);
        panelDeToggleButtonLayout.setHorizontalGroup(
            panelDeToggleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeToggleButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeToggleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeToggleButtonLayout.createSequentialGroup()
                        .addComponent(toggleButtonBrowser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleButtonMail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleButtonUser))
                    .addGroup(panelDeToggleButtonLayout.createSequentialGroup()
                        .addComponent(toggleButtonEnter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleButtonTab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleButtonPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleButtonEnter2)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelDeToggleButtonLayout.setVerticalGroup(
            panelDeToggleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeToggleButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeToggleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleButtonMail)
                    .addComponent(toggleButtonUser)
                    .addComponent(toggleButtonBrowser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDeToggleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleButtonEnter2)
                    .addComponent(toggleButtonPassword)
                    .addComponent(toggleButtonEnter)
                    .addComponent(toggleButtonTab))
                .addContainerGap())
        );

        buttonLimpiar.setText("Limpiar");
        buttonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDeTextFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelDeToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonEjecutar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonLimpiar))
                            .addComponent(panelNumeros1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDeTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelDeToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInsertar)
                    .addComponent(buttonEjecutar)
                    .addComponent(buttonLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNumeros1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.WEST);

        panelCenter.setLayout(new java.awt.CardLayout());
        panelCenter.add(panelInicio2, "cardInicio");

        jScrollPane1.setViewportView(tableRegistro);

        panelCenter.add(jScrollPane1, "cardTabla");

        add(panelCenter, java.awt.BorderLayout.CENTER);

        buttonFacebook.setText("Facebook");
        buttonFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFacebookActionPerformed(evt);
            }
        });

        buttonGoogle.setText("Google");
        buttonGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoogleActionPerformed(evt);
            }
        });

        buttonTwiter.setText("Twiter");
        buttonTwiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwiterActionPerformed(evt);
            }
        });

        buttonTuCuate.setText("Tu Cuate");
        buttonTuCuate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTuCuateActionPerformed(evt);
            }
        });

        buttonBrowser.setText("Browser");
        buttonBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBrowserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(381, Short.MAX_VALUE)
                .addComponent(buttonFacebook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonGoogle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTwiter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTuCuate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBrowser))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFacebook)
                    .addComponent(buttonGoogle)
                    .addComponent(buttonTwiter)
                    .addComponent(buttonTuCuate)
                    .addComponent(buttonBrowser))
                .addContainerGap())
        );

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertarActionPerformed
        // TODO add your handling code here:
        // registro = new Registro();
        if(isResgistro()){
            registro.setUrl(textFieldUrl.getText());
            registro.setNombre(textFieldNombre.getText());
            registro.setMailCelRecuperar(textFieldRecuperar.getText());
            registro.setMail(textFieldMail.getText());
            registro.setUser(textFieldUser.getText());
            registro.setPassword(textFieldPassword.getText());
            
            registro.setMailEnter(toggleButtonMail.isSelected());
            registro.setUserEnter(toggleButtonUser.isSelected());
            registro.setEnter(toggleButtonEnter.isSelected());
            registro.setPasswordEnter(toggleButtonPassword.isSelected());
            registro.setEnter2(toggleButtonEnter2.isSelected());
            if(registro.getId().equals("")){
                UUID uuid = UUID.randomUUID();
               
                registro.setId(uuid.toString());
                tableRegistro.addRegistro(registro);
                limpiar();
            }
            else{
                tableRegistro.update(registro);
                JOptionPane.showMessageDialog(this,"Datos se actualizaron correctamente");
                
            }  
                
            
            
        }
    }//GEN-LAST:event_buttonInsertarActionPerformed

    private void buttonEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEjecutarActionPerformed
      
        JOptionPane.showMessageDialog(this,new  String(DatosDelRegistro.getCodigoClase()));
    }//GEN-LAST:event_buttonEjecutarActionPerformed

    public boolean isResgistro(){
        if(textFieldUrl.getText().equals("")){
            textFieldUrl.requestFocus();
            return false;
        }
        else if(textFieldNombre.getText().equals("")){
            textFieldNombre.requestFocus();
            return false;
        }

        else if(textFieldMail.getText().equals("")){
            textFieldMail.requestFocus();
            return false;
        }

        if(textFieldPassword.getText().equals("")){
            textFieldPassword.requestFocus();
            return false;
        }
        return true;
    }
    private void toggleButtonMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonMailActionPerformed
        // TODO add your handling code here:
        if(toggleButtonUser.isSelected()){
            toggleButtonUser.setSelected(false);
        }
    }//GEN-LAST:event_toggleButtonMailActionPerformed

    private void toggleButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonUserActionPerformed
        // TODO add your handling code here:
        if(toggleButtonMail.isSelected()){
            toggleButtonMail.setSelected(false);
        }
    }//GEN-LAST:event_toggleButtonUserActionPerformed

    private void buttonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbrirActionPerformed
        // TODO add your handling code here:
        DatosDelRegistroInput ti = new DatosDelRegistroInput();
       
        JFileChooser fchooser = new JFileChooser(System.getProperty("user.dir","."));
        
        FileFilter filter = new FileNameExtensionFilter("Extencion", "ecs");
        fchooser.setAcceptAllFileFilterUsed(false);
        fchooser.addChoosableFileFilter(filter);
        
         int estado = fchooser.showOpenDialog(this);
         if(estado == JFileChooser.APPROVE_OPTION){
            
            try {
                ti.abrir(fchooser.getSelectedFile());
                DatosDelRegistro dr = ti.leer();
                ti.cerra();
  
                Object o = (Object)this.getRootPane().getParent();
                JDialog d;
                if(o instanceof Dialog){
                    d = new JDialog((Dialog)o); 
                }
                else if(o instanceof Frame){
                    d = new JDialog((Frame)o);
                }
                else{
                    d = new JDialog();
                }
                d.setTitle("Colocar un Codigo asta 6 digitos");
                PanelNumeros pn = new PanelNumeros();
                pn.setMensaje("Ingrese codigo para habrir el Archivo ");
                //Acccin del Botton Intro
                pn.addActionPermed((e) -> {
                    if(Util.comparar(pn.charPassword(),dr.getCodigo())){
                        d.setVisible(false);
                        tableRegistro.addListRegistro(dr.getLista());
                        CardLayout cardLayout = (CardLayout)panelCenter.getLayout();
                        cardLayout.show(panelCenter, "cardTabla");  
                    }
                    else
                        pn.setMensaje("Codigo incorrecto");
                });

                
                d.add(pn);
                d.setModal(true);
                d.pack();
                d.setLocationRelativeTo(null);
                d.setVisible(true); 
                
                
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(PanelRegistro2.class.getName()).log(Level.SEVERE, null, ex);
                
            }
         }
        
    }//GEN-LAST:event_buttonAbrirActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt){
        
        DatosDelRegistro.setNuevo(true);
        DatosDelRegistro.setGuardar(true);
        
        Object o = (Object)this.getRootPane().getParent();
        JDialog d;
        if(o instanceof Dialog){
            d = new JDialog((Dialog)o); 
        }
        else if(o instanceof Frame){
            d = new JDialog((Frame)o);
        }
        else{
            d = new JDialog();
        }
        d.setTitle("Colocar un Codigo asta 6 digitos");
        PanelNumeros pn = new PanelNumeros();
        pn.setMensaje("Ingrese nuevo codigo de  seguridad de 4 a 6 digitos. <p> ¡No olvide el codigo para abrir el archivo despues!");
        pn.addActionPermed((e) -> {
            if(pn.charPassword()!=null){
                DatosDelRegistro.setCodigoClase(pn.charPassword());
                d.setVisible(false);
                JOptionPane.showMessageDialog(this,"Codigo Guardado Correctamente");
                //PanelRegistro2 pr = (PanelRegistro2) this.getParent();
                CardLayout cardLayout = (CardLayout)panelCenter.getLayout();
                cardLayout.show(panelCenter, "cardTabla");
                disable(true);
            }
        });
        d.add(pn);
        d.setModal(true);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
         
    }
    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        DatosDelRegistroInput ti = new DatosDelRegistroInput();
       
        JFileChooser fchooser = new JFileChooser(System.getProperty("user.dir","."));
        
        FileFilter filter = new FileNameExtensionFilter("Extencion", "ecs");
        fchooser.setAcceptAllFileFilterUsed(false);
        fchooser.addChoosableFileFilter(filter);
        
         int estado = fchooser.showOpenDialog(this);
         if(estado == JFileChooser.APPROVE_OPTION){
            
            try {
                ti.abrir(fchooser.getSelectedFile());
                DatosDelRegistro dr = ti.leer();
                ti.cerra();
  
                Object o = (Object)this.getRootPane().getParent();
                JDialog d;
                if(o instanceof Dialog){
                    d = new JDialog((Dialog)o); 
                }
                else if(o instanceof Frame){
                    d = new JDialog((Frame)o);
                }
                else{
                    d = new JDialog();
                }
                d.setTitle("Colocar un Codigo asta 6 digitos");
                PanelNumeros pn = new PanelNumeros();
                pn.setMensaje("Ingrese codigo para habrir el Archivo ");
                //Acccin del Botton Intro
                pn.addActionPermed((e) -> {
                    if(Util.comparar(pn.charPassword(),dr.getCodigo())){
                        d.setVisible(false);
                        tableRegistro.addListRegistro(dr.getLista());
                        CardLayout cardLayout = (CardLayout)panelCenter.getLayout();
                        cardLayout.show(panelCenter, "cardTabla");
                        disable(true);
                    }
                    else
                        pn.setMensaje("Codigo incorrecto");
                });

                
                d.add(pn);
                d.setModal(true);
                d.pack();
                d.setLocationRelativeTo(null);
                d.setVisible(true); 
                
                
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(PanelRegistro2.class.getName()).log(Level.SEVERE, null, ex);
                
            }
         }
        
    } 
    private void buttonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInicioActionPerformed
        // TODO add your handling code here:
        limpiar();
        tableRegistro.limpiar();
        DatosDelRegistro.nuevo();
        CardLayout cardLayout = (CardLayout)panelCenter.getLayout();
        cardLayout.show(panelCenter,"cardInicio");
        disable(false);
    }//GEN-LAST:event_buttonInicioActionPerformed

    private void buttonFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacebookActionPerformed
        // TODO add your handling code here:
        textFieldUrl.setText("www.facebook.com");
        textFieldNombre.setText("FACEBOOK");
        textFieldMail.setText("escuela.schumager@gmail.com");
        textFieldUser.setText("Faacebook");
        textFieldPassword.setText("Schum319461ageran");
        
        toggleButtonMail.setSelected(true);
        toggleButtonUser.setSelected(false);
        toggleButtonEnter.setSelected(false);
        toggleButtonPassword.setSelected(true);
        toggleButtonEnter2.setSelected(true);
    }//GEN-LAST:event_buttonFacebookActionPerformed

    private void buttonGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoogleActionPerformed
        // TODO add your handling code here:
        textFieldUrl.setText("www.gmail.com");
        textFieldNombre.setText("GMAIL");
        textFieldMail.setText("escuela.schumager@gmail.com");
        textFieldUser.setText("EscuelaSchumager");
        textFieldPassword.setText("chiqui11042016lina");
        
        toggleButtonMail.setSelected(true);
        toggleButtonUser.setSelected(false);
        toggleButtonEnter.setSelected(true);
        toggleButtonPassword.setSelected(true);
        toggleButtonEnter2.setSelected(true);
    }//GEN-LAST:event_buttonGoogleActionPerformed

    private void buttonTwiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwiterActionPerformed
        // TODO add your handling code here:
        textFieldUrl.setText("www.x.com");
        textFieldNombre.setText("TWITER");
        textFieldMail.setText("escuela.schumager@gmail.com");
        textFieldUser.setText("@EscuelaSchumager");
        textFieldPassword.setText("T319461ter");
        
        toggleButtonMail.setSelected(true);
        toggleButtonUser.setSelected(false);
        toggleButtonEnter.setSelected(true);
        toggleButtonPassword.setSelected(true);
        toggleButtonEnter2.setSelected(true);

    }//GEN-LAST:event_buttonTwiterActionPerformed

    private void buttonTuCuateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTuCuateActionPerformed
        // TODO add your handling code here:
        textFieldUrl.setText("www.tucuate.com");
        textFieldNombre.setText("TU CUATE");
        textFieldMail.setText("hos.fl700@gmail.com");
        textFieldUser.setText("71247983");
        textFieldPassword.setText("Tu6572175cuate");
       
        toggleButtonMail.setSelected(false);
        toggleButtonUser.setSelected(true);
        toggleButtonEnter.setSelected(false);
        toggleButtonPassword.setSelected(true);
        toggleButtonEnter2.setSelected(true);
    }//GEN-LAST:event_buttonTuCuateActionPerformed

    private void buttonBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBrowserActionPerformed
        /*try {
            // TODO add your handling code here:
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + textFieldUrl.getText());

        } catch (IOException ex) {
            Logger.getLogger(PanelRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        tableRegistro.mostrar();
        
    }//GEN-LAST:event_buttonBrowserActionPerformed

    private void toggleButtonBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonBrowserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toggleButtonBrowserActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        // TODO add your handling code here:
        DatosDelRegistroOutput tableOutput = new DatosDelRegistroOutput();
        DatosDelRegistro dr = new DatosDelRegistro();
        dr.setLista(tableRegistro.getList());
        dr.setCodigo(DatosDelRegistro.getCodigoClase());
        
        JFileChooser fchooser = new JFileChooser(System.getProperty("user.dir","."));
        fchooser.setAcceptAllFileFilterUsed(false);
        
        FileFilter filter = new FileNameExtensionFilter("Extencion", "ecs");
        fchooser.addChoosableFileFilter(filter);
       // fchooser.setSelectedFile(new File("lista.ecs"));
        int estado = fchooser.showSaveDialog(this);            
        if(estado == JFileChooser.APPROVE_OPTION){
            try {
                
                fchooser.getName();
                tableOutput.abrir(fchooser.getSelectedFile());
                
                tableOutput.guardar(dr);
                tableOutput.cerrar();
            } catch (IOException ex) {
                Logger.getLogger(PanelRegistro2.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
        /*try {
            tableOutput.abrir();
            tableOutput.guardar(dr);
            tableOutput.cerrar();
        } catch (IOException ex) {
            Logger.getLogger(PanelRegistro2.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void buttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_buttonLimpiarActionPerformed
    
    public void loadComponets(Registro r){
        registro = r;
        textFieldUrl.setText(registro.getUrl());
        textFieldNombre.setText(registro.getNombre());
        textFieldRecuperar.setText(r.getMailCelRecuperar());
        textFieldMail.setText(registro.getMail());
        textFieldUser.setText(registro.getUser());
        textFieldPassword.setText(registro.getPassword());
        
        toggleButtonMail.setSelected(registro.isMailEnter());
        toggleButtonUser.setSelected(registro.isUserEnter());
        toggleButtonEnter.setSelected(registro.isEnter());
        toggleButtonPassword.setSelected(registro.isPasswordEnter());
        toggleButtonEnter2.setSelected(registro.isEnter2());
        
    }
    public void limpiar(){
        registro = new Registro();
        textFieldUrl.setText("");
        textFieldNombre.setText("");
        textFieldRecuperar.setText("");
        textFieldMail.setText("");
        textFieldUser.setText("");
        textFieldPassword.setText("");
        
        toggleButtonBrowser.setSelected(false);
        toggleButtonMail.setSelected(false);
        toggleButtonUser.setSelected(false);
        toggleButtonEnter.setSelected(false);
        toggleButtonTab.setSelected(false);
        toggleButtonPassword.setSelected(false);
        toggleButtonEnter2.setSelected(false);
        textFieldUrl.requestFocus();
        
    }
    public void disable(boolean  disable){
        //toolbar.setEnabled(disable);
        panelDeTextFields.setEnabled(disable);
        textFieldUrl.setEnabled(disable);
        textFieldNombre.setEnabled(disable);
        textFieldRecuperar.setEnabled(disable);
        textFieldMail.setEnabled(disable);
        textFieldUser.setEnabled(disable);
        textFieldPassword.setEnabled(disable);
        //Enabled ToggleButton
        panelDeToggleButton.setEnabled(disable);
        toggleButtonBrowser.setEnabled(disable);
        toggleButtonMail.setEnabled(disable);
        toggleButtonUser.setEnabled(disable);
        toggleButtonEnter.setEnabled(disable);
        toggleButtonTab.setEnabled(disable);
        toggleButtonPassword.setEnabled(disable);
        toggleButtonEnter2.setEnabled(disable);
        //Enable Botones
        buttonInsertar.setEnabled(disable);
        buttonEjecutar.setEnabled(disable);
        buttonLimpiar.setEnabled(disable);
        //Botones de la barra
        buttonAbrir.setEnabled(disable);
        buttonGuardar.setEnabled(disable);
        buttonInicio.setEnabled(disable);
        panelNumeros1.setEnabled(disable);
        buttonTwiter.setEnabled(disable);
                
                
    }

    public TableRegistro getTableRegistro() {
        return tableRegistro;
    }

    public void setTableRegistro(TableRegistro tableRegistro) {
        this.tableRegistro = tableRegistro;
    }
    

    public TextFieldLabel getTextFieldNombre() {
        return textFieldNombre;
    }

    public void setTextFieldNombre(TextFieldLabel textFieldNombre) {
        this.textFieldNombre = textFieldNombre;
    }
     Registro registro; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbrir;
    private javax.swing.JButton buttonBrowser;
    private javax.swing.JButton buttonEjecutar;
    private javax.swing.JButton buttonFacebook;
    private javax.swing.JButton buttonGoogle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonInicio;
    private javax.swing.JButton buttonInsertar;
    private javax.swing.JButton buttonLimpiar;
    private javax.swing.JButton buttonTuCuate;
    private javax.swing.JButton buttonTwiter;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelDeTextFields;
    private javax.swing.JPanel panelDeToggleButton;
    private com.schumager.mypassword.view.PanelInicio panelInicio2;
    private com.schumager.mypassword.view.PanelNumeros panelNumeros1;
    private com.schumager.mypassword.view.table.TableRegistro tableRegistro;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldMail;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldNombre;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldPassword;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldRecuperar;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldUrl;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldUser;
    private javax.swing.JToggleButton toggleButtonBrowser;
    private javax.swing.JToggleButton toggleButtonEnter;
    private javax.swing.JToggleButton toggleButtonEnter2;
    private javax.swing.JToggleButton toggleButtonMail;
    private javax.swing.JToggleButton toggleButtonPassword;
    private javax.swing.JToggleButton toggleButtonTab;
    private javax.swing.JToggleButton toggleButtonUser;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
