/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.schumager.mypassword.view;

import com.schumager.mypassword.model.Registro;
import com.schumager.mypassword.model.util.EjecutarBoot;
import javax.swing.BoxLayout;
import javax.swing.JButton;

/**
 *
 * @author Schumager
 */
public class PanelEjecutarDirecto extends javax.swing.JPanel {

    /**
     * Creates new form PanelEjecutarDirecto
     */
    public PanelEjecutarDirecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAgregar = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        buttonAgregar.setText("+");
        add(buttonAgregar);
    }// </editor-fold>//GEN-END:initComponents
    public void agregarBoton(Registro r){
        JButton  boton = new JButton();
        boton.setText(r.getNombre());
        boton.addActionListener((e)->{
            EjecutarBoot.ingresar(r);
        });
        add(boton);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregar;
    // End of variables declaration//GEN-END:variables
}
