/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.schumager.mypassword.view;

import com.schumager.mypassword.model.DatosDelRegistro;
import java.awt.event.ActionListener;

/**
 *
 * @author Schumager
 */
public class PanelNumeros extends javax.swing.JPanel {

    /**
     * Creates new form PanelNumeros
     */
    public PanelNumeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        labelMensaje = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        passwordField = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonIntro = new javax.swing.JButton();
        button0 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        labelMensaje.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        labelMensaje.setForeground(new java.awt.Color(255, 51, 102));
        labelMensaje.setText("Mensaje");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);

        passwordField.setEditable(false);
        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordField)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(4, 3, 5, 5));

        button7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        jPanel2.add(button7);

        button8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        jPanel2.add(button8);

        button9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        jPanel2.add(button9);

        button4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel2.add(button4);

        button5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel2.add(button5);

        button6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        jPanel2.add(button6);

        button1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel2.add(button1);

        button2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel2.add(button2);

        button3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel2.add(button3);

        buttonClear.setBackground(new java.awt.Color(255, 0, 51));
        buttonClear.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(255, 255, 255));
        buttonClear.setText("CLEAR");
        buttonClear.setBorderPainted(false);
        buttonClear.setMargin(new java.awt.Insets(2, 5, 3, 5));
        buttonClear.setOpaque(true);
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClear);

        buttonIntro.setBackground(new java.awt.Color(0, 204, 51));
        buttonIntro.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        buttonIntro.setForeground(new java.awt.Color(255, 255, 255));
        buttonIntro.setText("INTRO");
        buttonIntro.setBorderPainted(false);
        buttonIntro.setMargin(new java.awt.Insets(2, 5, 3, 5));
        buttonIntro.setOpaque(true);
        jPanel2.add(buttonIntro);

        button0.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        button0.setText("C");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });
        jPanel2.add(button0);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        if(passwordField.getPassword().length<6)
            passwordField.setText(String.copyValueOf(passwordField.getPassword())+"7");
        else
            getToolkit().beep();
    }//GEN-LAST:event_button7ActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        passwordField.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        // TODO add your handling code here:
         if(passwordField.getPassword().length>0){
             char []charPass = passwordField.getPassword();
             String password = new String(charPass, 0, charPass.length-1);
             passwordField.setText(password);
         }
         else
            getToolkit().beep();

    }//GEN-LAST:event_button0ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
         if(passwordField.getPassword().length<max)
            passwordField.setText(String.copyValueOf(passwordField.getPassword())+"3");
        else
            getToolkit().beep();
    }//GEN-LAST:event_button3ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
         if(passwordField.getPassword().length<max)
            passwordField.setText(String.copyValueOf(passwordField.getPassword())+"6");
        else
            getToolkit().beep();
    }//GEN-LAST:event_button6ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
         if(passwordField.getPassword().length<max)
            passwordField.setText(String.copyValueOf(passwordField.getPassword())+"4");
        else
            getToolkit().beep();
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
         if(passwordField.getPassword().length<max)
            passwordField.setText(String.copyValueOf(passwordField.getPassword())+"5");
        else
            getToolkit().beep();
    }//GEN-LAST:event_button5ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        if(passwordField.getPassword().length<max)
            passwordField.setText(String.copyValueOf(passwordField.getPassword())+"8");
        else
            getToolkit().beep();
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
         if(passwordField.getPassword().length<max)
            passwordField.setText(String.copyValueOf(passwordField.getPassword())+"9");
        else
            getToolkit().beep();
    }//GEN-LAST:event_button9ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:        
         if(passwordField.getPassword().length<max)
            passwordField.setText(String.copyValueOf(passwordField.getPassword())+"1");
        else
            getToolkit().beep();
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
         if(passwordField.getPassword().length<max)
            passwordField.setText(String.copyValueOf(passwordField.getPassword())+"2");
        else
            getToolkit().beep();
    }//GEN-LAST:event_button2ActionPerformed
    @Override
    public void setEnabled(boolean enabled){
        super.setEnabled(enabled);
        button0.setEnabled(enabled);
        button1.setEnabled(enabled);
        button2.setEnabled(enabled);
        button3.setEnabled(enabled);
        button4.setEnabled(enabled);
        button5.setEnabled(enabled);
        button6.setEnabled(enabled);
        button7.setEnabled(enabled);
        button8.setEnabled(enabled);
        button9.setEnabled(enabled);
        
        buttonIntro.setEnabled(enabled);
        buttonClear.setEnabled(enabled);
        
        labelMensaje.setEnabled(enabled);
    }
    public void setMensaje(String mensaje){
        labelMensaje.setText("<html>"+mensaje+"</html>");
    }
    public void addActionPermed(ActionListener action){
        buttonIntro.addActionListener(action);
    }
    public char [] charPassword(){
        /*    if(passwordField.getPassword().length>=min&&passwordField.getPassword().length<=max){
            return passwordField.getPassword();
        }
        char[]character = new char[1];
        character[0]= '1';
        return character;*/
        return passwordField.getPassword();
    }
    private byte min = 4;
    private byte max = 6;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonIntro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
