/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.schumager.mypassword.view;

import com.schumager.mypassword.model.JRobot;
import com.schumager.mypassword.model.Registro;
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Schumager
 */
public class PanelRegistro extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistro
     */
    public PanelRegistro() {
        initComponents();
        registro = new Registro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        textFieldUrl = new com.schumager.mypassword.view.components.TextField();
        textFieldNombre = new com.schumager.mypassword.view.components.TextField();
        textFieldMail = new com.schumager.mypassword.view.components.TextField();
        textFieldUser = new com.schumager.mypassword.view.components.TextField();
        buttonGuardar = new javax.swing.JButton();
        buttonIngresar = new javax.swing.JButton();
        toggleButtonMail = new javax.swing.JToggleButton();
        toggleButtonUser = new javax.swing.JToggleButton();
        toggleButtonEnter = new javax.swing.JToggleButton();
        toggleButtonPassword = new javax.swing.JToggleButton();
        toggleButtonEnter2 = new javax.swing.JToggleButton();
        buttonFacebook = new javax.swing.JButton();
        buttonGoogle = new javax.swing.JButton();
        buttonTwiter = new javax.swing.JButton();
        buttonTuCuate = new javax.swing.JButton();
        textFieldPassword = new com.schumager.mypassword.view.components.TextFieldLabel();
        buttonBrowser = new javax.swing.JButton();

        textFieldUrl.setCantidad(50);
        textFieldUrl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldUrl.setName(""); // NOI18N
        textFieldUrl.setTitle("Inserte  Direccion de la pagina");

        textFieldNombre.setCantidad(50);
        textFieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldNombre.setName(""); // NOI18N
        textFieldNombre.setTitle("Inserte Nombre de la Pagina");

        textFieldMail.setCantidad(50);
        textFieldMail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldMail.setName(""); // NOI18N
        textFieldMail.setTitle("Inserte Correo Electronico");

        textFieldUser.setCantidad(50);
        textFieldUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldUser.setName(""); // NOI18N
        textFieldUser.setTitle("Inserte Usuario");

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        buttonIngresar.setText("Ingresar");
        buttonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIngresarActionPerformed(evt);
            }
        });

        toggleButtonMail.setText("Correo >");
        toggleButtonMail.setMargin(new java.awt.Insets(2, 5, 3, 5));
        toggleButtonMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonMailActionPerformed(evt);
            }
        });

        toggleButtonUser.setText("Usuario >");
        toggleButtonUser.setMargin(new java.awt.Insets(2, 5, 3, 5));
        toggleButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonUserActionPerformed(evt);
            }
        });

        toggleButtonEnter.setText("Enter >");
        toggleButtonEnter.setMargin(new java.awt.Insets(2, 5, 3, 5));

        toggleButtonPassword.setText("Contraseña >");
        toggleButtonPassword.setMargin(new java.awt.Insets(2, 5, 3, 5));

        toggleButtonEnter2.setText("Enter >");
        toggleButtonEnter2.setMargin(new java.awt.Insets(2, 5, 3, 5));

        buttonFacebook.setText("Facebook");
        buttonFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFacebookActionPerformed(evt);
            }
        });

        buttonGoogle.setText("Google");
        buttonGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoogleActionPerformed(evt);
            }
        });

        buttonTwiter.setText("Twiter");
        buttonTwiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwiterActionPerformed(evt);
            }
        });

        buttonTuCuate.setText("Tu Cuate");
        buttonTuCuate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTuCuateActionPerformed(evt);
            }
        });

        textFieldPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldPassword.setTextLabel("Ver");
        textFieldPassword.setTipoDeCaracteres(4);
        textFieldPassword.setTitle("Inserte Contraseña");

        buttonBrowser.setText("Browser");
        buttonBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBrowserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(buttonGuardar)
                        .addGap(37, 37, 37)
                        .addComponent(buttonIngresar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toggleButtonMail)
                        .addGap(0, 0, 0)
                        .addComponent(toggleButtonUser)
                        .addGap(0, 0, 0)
                        .addComponent(toggleButtonEnter)
                        .addGap(0, 0, 0)
                        .addComponent(toggleButtonPassword)
                        .addGap(0, 0, 0)
                        .addComponent(toggleButtonEnter2)))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonFacebook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldUser, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(textFieldMail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(textFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(textFieldUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonGoogle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTwiter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTuCuate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonBrowser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFacebook)
                    .addComponent(buttonGoogle)
                    .addComponent(buttonTwiter)
                    .addComponent(buttonTuCuate)
                    .addComponent(buttonBrowser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleButtonMail)
                    .addComponent(toggleButtonUser)
                    .addComponent(toggleButtonEnter)
                    .addComponent(toggleButtonPassword)
                    .addComponent(toggleButtonEnter2))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGuardar)
                    .addComponent(buttonIngresar))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        // TODO add your handling code here:
        if(isResgistro()){
            registro.setUrl(textFieldUrl.getText());
            registro.setNombre(textFieldNombre.getText());
            registro.setMail(textFieldMail.getText());
            registro.setUser(textFieldUser.getText());
            registro.setPassword(textFieldPassword.getText());
        }
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void buttonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIngresarActionPerformed
        // TODO add your handling code here:
       /* if(registro.getUser().equals("")){
            JOptionPane.showMessageDialog(this, "Registre Usuario");
            return;
        }
        if(registro.getPassword().equals("")){
            JOptionPane.showMessageDialog(this, "Registre Password");
            return;
        }*/
       
            
        Robot robot;
            try {
                boolean capsActivo = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
                robot = new Robot();
                if(capsActivo){
                    robot.keyPress(KeyEvent.VK_CAPS_LOCK);
                    robot.keyRelease(KeyEvent.VK_CAPS_LOCK);
                }
                                
                //Alt Tab cambio de pantalla a Pagina de CUPAD
                robot.keyPress(KeyEvent.VK_ALT);
                robot.delay(100);
                robot.keyPress(KeyEvent.VK_TAB);
                robot.delay(100);
                robot.keyRelease(KeyEvent.VK_TAB);
                robot.delay(100);
                robot.keyRelease(KeyEvent.VK_ALT);
                
                robot.delay(500);

                ///Escribre Ci
                //byte user [] = registro.getUser().getBytes();
                JRobot jRobot = new JRobot();
                if(toggleButtonMail.isSelected()){
                    byte mail [] = textFieldMail.getText().getBytes();

                    for (int i = 0 ; i < mail.length ; i++) {
                   
                    jRobot.keyPressed((char)mail[i]);
                     
                    robot.delay(100);
      

                   }
                }
                if(toggleButtonUser.isSelected()){
                    byte user [] = textFieldUser.getText().getBytes();

                    for (int i = 0 ; i < user.length ; i++) {

                        jRobot.keyPressed((char)user[i]);

                        robot.delay(100);

                    }
                }
                if(toggleButtonEnter.isSelected()){
                   robot.keyPress(KeyEvent.VK_ENTER);
                   robot.keyRelease(KeyEvent.VK_ENTER); 
                   robot.delay(3000);
                }
                else{
                    if(toggleButtonMail.isSelected()||toggleButtonUser.isSelected()){
                        if(toggleButtonPassword.isSelected()){
                            robot.keyPress(KeyEvent.VK_TAB);
                            robot.keyRelease(KeyEvent.VK_TAB);
                            robot.delay(100);
                        }
                    }
                    
                }
                if(toggleButtonPassword.isSelected()){
                    
                    byte password [] = textFieldPassword.getText().getBytes();
                    for (int i = 0 ; i < password.length ; i++) {

                        jRobot.keyPressed((char)password[i]);
                        robot.delay(100);
                    }
                }
                if(toggleButtonEnter2.isSelected()){
                    robot.keyPress(KeyEvent.VK_ENTER);
                    robot.keyRelease(KeyEvent.VK_ENTER);
                }
               } 
              catch (AWTException  ex) {
               Logger.getLogger(PanelRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_buttonIngresarActionPerformed

    public boolean isResgistro(){
        if(textFieldUrl.getText().equals("")){
            return false;
        }
        if(textFieldNombre.getText().equals("")){
            return false;
        }
        if(textFieldMail.getText().equals("")){
            return false;
        }
        if(textFieldUser.getText().equals("")){
            return false;
        }
        if(textFieldPassword.getText().equals("")){
            return false;
        }
        return true;
    }
    private void toggleButtonMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonMailActionPerformed
        // TODO add your handling code here:
        if(toggleButtonUser.isSelected()){
            toggleButtonUser.setSelected(false);
        }
    }//GEN-LAST:event_toggleButtonMailActionPerformed

    private void toggleButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonUserActionPerformed
        // TODO add your handling code here:
        if(toggleButtonMail.isSelected()){
            toggleButtonMail.setSelected(false);
        }
    }//GEN-LAST:event_toggleButtonUserActionPerformed

    private void buttonFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacebookActionPerformed
        // TODO add your handling code here:
        textFieldUrl.setText("www.facebook.com");
        textFieldNombre.setText("FACEBOOK");
        textFieldMail.setText("escuela.schumager@gmail.com");
        textFieldUser.setText("Faacebook");
        textFieldPassword.setText("Schum319461ageran");
    }//GEN-LAST:event_buttonFacebookActionPerformed

    private void buttonGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoogleActionPerformed
        // TODO add your handling code here:
        textFieldUrl.setText("www.gmail.com");
        textFieldNombre.setText("GMAIL");
        textFieldMail.setText("escuela.schumager@gmail.com");
        textFieldUser.setText("EscuelaSchumager");
        textFieldPassword.setText("chiqui11042016lina");
    }//GEN-LAST:event_buttonGoogleActionPerformed

    private void buttonTwiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwiterActionPerformed
        // TODO add your handling code here:
        textFieldUrl.setText("www.x.com");
        textFieldNombre.setText("TWITER");
        textFieldMail.setText("escuela.schumager@gmail.com");
        textFieldUser.setText("@EscuelaSchumager");
        textFieldPassword.setText("T319461ter");
        
    }//GEN-LAST:event_buttonTwiterActionPerformed

    private void buttonTuCuateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTuCuateActionPerformed
        // TODO add your handling code here:
        textFieldUrl.setText("www.tucuate.com");
        textFieldNombre.setText("TU CUATE");
        textFieldMail.setText("hos.fl700@gmail.com");
        textFieldUser.setText("71247983");
        textFieldPassword.setText("Tu6572175cuate");
    }//GEN-LAST:event_buttonTuCuateActionPerformed

    private void buttonBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBrowserActionPerformed
        try {
            // TODO add your handling code here:
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + textFieldUrl.getText());
            
        } catch (IOException ex) {
            Logger.getLogger(PanelRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBrowserActionPerformed
    
    Registro registro; 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBrowser;
    private javax.swing.JButton buttonFacebook;
    private javax.swing.JButton buttonGoogle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonIngresar;
    private javax.swing.JButton buttonTuCuate;
    private javax.swing.JButton buttonTwiter;
    private com.schumager.mypassword.view.components.TextField textFieldMail;
    private com.schumager.mypassword.view.components.TextField textFieldNombre;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldPassword;
    private com.schumager.mypassword.view.components.TextField textFieldUrl;
    private com.schumager.mypassword.view.components.TextField textFieldUser;
    private javax.swing.JToggleButton toggleButtonEnter;
    private javax.swing.JToggleButton toggleButtonEnter2;
    private javax.swing.JToggleButton toggleButtonMail;
    private javax.swing.JToggleButton toggleButtonPassword;
    private javax.swing.JToggleButton toggleButtonUser;
    // End of variables declaration//GEN-END:variables
}
