/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.schumager.mypassword.view;

import com.schumager.mypassword.model.DatosDelRegistro;
import java.awt.CardLayout;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Schumager
 */
public class PanelInicio extends javax.swing.JPanel{

    /**
     * Creates new form PanelInicio
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonNuevo = new javax.swing.JButton();
        buttonAbrir = new javax.swing.JButton();

        buttonNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/schumager/mypassword/images/nuevo.png"))); // NOI18N
        buttonNuevo.setText("Nuevo");
        buttonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNuevo.setPreferredSize(new java.awt.Dimension(130, 130));
        buttonNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonAbrir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/schumager/mypassword/images/abrir.png"))); // NOI18N
        buttonAbrir.setText("Abrir");
        buttonAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAbrir.setInheritsPopupMenu(true);
        buttonAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(buttonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(buttonAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void addAbrirActionPerformed(ActionListener action){
        buttonAbrir.addActionListener(action);
    }
    public void addNuevoActionPerformed(ActionListener action){
        buttonNuevo.addActionListener(action);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbrir;
    private javax.swing.JButton buttonNuevo;
    // End of variables declaration//GEN-END:variables

}
