/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.schumager.mypassword.view;

import com.schumager.mypassword.model.JRobot;
import com.schumager.mypassword.model.Registro;
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Schumager
 */
public class PanelRegistro1 extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistro
     */
    public PanelRegistro1() {
        initComponents();
        registro = new Registro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        textFieldUrl = new com.schumager.mypassword.view.components.TextFieldLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jPanel2 = new javax.swing.JPanel();
        textFieldPassword = new com.schumager.mypassword.view.components.TextFieldLabel();
        buttonGuardar = new javax.swing.JButton();
        buttonIngresar = new javax.swing.JButton();
        textFieldUser = new com.schumager.mypassword.view.components.TextFieldLabel();
        textFieldMail = new com.schumager.mypassword.view.components.TextFieldLabel();
        textFieldRecuperar = new com.schumager.mypassword.view.components.TextFieldLabel();
        textFieldNombre = new com.schumager.mypassword.view.components.TextFieldLabel();
        panelNumeros1 = new com.schumager.mypassword.view.PanelNumeros();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegistro = new com.schumager.mypassword.view.table.TableRegistro();
        jPanel3 = new javax.swing.JPanel();
        toggleButtonMail = new javax.swing.JToggleButton();
        toggleButtonUser = new javax.swing.JToggleButton();
        toggleButtonEnter = new javax.swing.JToggleButton();
        toggleButtonPassword = new javax.swing.JToggleButton();
        toggleButtonEnter2 = new javax.swing.JToggleButton();
        buttonFacebook = new javax.swing.JButton();
        buttonGoogle = new javax.swing.JButton();
        buttonTwiter = new javax.swing.JButton();
        buttonTuCuate = new javax.swing.JButton();
        buttonBrowser = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setMinimumSize(new java.awt.Dimension(201, 40));
        jToolBar1.add(jSeparator1);

        textFieldUrl.setCantidad(1000);
        textFieldUrl.setPreferredSize(new java.awt.Dimension(260, 35));
        textFieldUrl.setTextLabel("Ir");
        textFieldUrl.setTitle("Inserte direccion de la pagina de login");
        jToolBar1.add(textFieldUrl);
        jToolBar1.add(jSeparator3);

        jButton1.setText("Abrir");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Guardar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setText("Nuevo");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator2);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        textFieldPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textFieldPassword.setTextLabel("Copy");
        textFieldPassword.setTipoDeCaracteres(4);
        textFieldPassword.setTitle("Inserte Contraseña");

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        buttonIngresar.setText("Ingresar");
        buttonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIngresarActionPerformed(evt);
            }
        });

        textFieldUser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textFieldUser.setTextLabel("Copy");
        textFieldUser.setTitle("Insertar Usuario");

        textFieldMail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textFieldMail.setTextLabel("Copy");
        textFieldMail.setTitle("Insertar Correo Electronico");

        textFieldRecuperar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textFieldRecuperar.setTextLabel("Copy");
        textFieldRecuperar.setTitle("Correo y/o numero de recuperar");

        textFieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textFieldNombre.setTextLabel("Copy");
        textFieldNombre.setTitle("Inserte Nombre de la Pagina");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonIngresar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(textFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(textFieldRecuperar, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(textFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(panelNumeros1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNumeros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGuardar)
                    .addComponent(buttonIngresar)))
        );

        add(jPanel2, java.awt.BorderLayout.WEST);

        jScrollPane1.setViewportView(tableRegistro);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);

        toggleButtonMail.setText("Correo >");
        toggleButtonMail.setMargin(new java.awt.Insets(2, 5, 3, 5));
        toggleButtonMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonMailActionPerformed(evt);
            }
        });

        toggleButtonUser.setText("Usuario >");
        toggleButtonUser.setMargin(new java.awt.Insets(2, 5, 3, 5));
        toggleButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonUserActionPerformed(evt);
            }
        });

        toggleButtonEnter.setText("Enter >");
        toggleButtonEnter.setMargin(new java.awt.Insets(2, 5, 3, 5));

        toggleButtonPassword.setText("Contraseña >");
        toggleButtonPassword.setMargin(new java.awt.Insets(2, 5, 3, 5));

        toggleButtonEnter2.setText("Enter >");
        toggleButtonEnter2.setMargin(new java.awt.Insets(2, 5, 3, 5));

        buttonFacebook.setText("Facebook");
        buttonFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFacebookActionPerformed(evt);
            }
        });

        buttonGoogle.setText("Google");
        buttonGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoogleActionPerformed(evt);
            }
        });

        buttonTwiter.setText("Twiter");
        buttonTwiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwiterActionPerformed(evt);
            }
        });

        buttonTuCuate.setText("Tu Cuate");
        buttonTuCuate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTuCuateActionPerformed(evt);
            }
        });

        buttonBrowser.setText("Browser");
        buttonBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBrowserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(toggleButtonMail)
                .addGap(0, 0, 0)
                .addComponent(toggleButtonUser)
                .addGap(0, 0, 0)
                .addComponent(toggleButtonEnter)
                .addGap(0, 0, 0)
                .addComponent(toggleButtonPassword)
                .addGap(0, 0, 0)
                .addComponent(toggleButtonEnter2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonFacebook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonGoogle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTwiter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTuCuate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBrowser))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonFacebook)
                        .addComponent(buttonGoogle)
                        .addComponent(buttonTwiter)
                        .addComponent(buttonTuCuate)
                        .addComponent(buttonBrowser))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(toggleButtonMail)
                        .addComponent(toggleButtonUser)
                        .addComponent(toggleButtonEnter)
                        .addComponent(toggleButtonPassword)
                        .addComponent(toggleButtonEnter2)))
                .addContainerGap())
        );

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        // TODO add your handling code here:
        registro = new Registro();
        if(isResgistro()){
            registro.setUrl(textFieldUrl.getText());
            registro.setNombre(textFieldNombre.getText());
            registro.setMail(textFieldMail.getText());
            registro.setUser(textFieldUser.getText());
            registro.setPassword(textFieldPassword.getText());
            
            registro.setMailEnter(toggleButtonMail.isSelected());
            registro.setUserEnter(toggleButtonUser.isSelected());
            registro.setEnter(toggleButtonEnter.isSelected());
            registro.setPasswordEnter(toggleButtonPassword.isSelected());
            registro.setEnter2(toggleButtonEnter2.isSelected());
            
            tableRegistro.addRegistro(registro);
            
        }
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void buttonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIngresarActionPerformed
        // TODO add your handling code here:
       /* if(registro.getUser().equals("")){
            JOptionPane.showMessageDialog(this, "Registre Usuario");
            return;
        }
        if(registro.getPassword().equals("")){
            JOptionPane.showMessageDialog(this, "Registre Password");
            return;
        }*/
       
            
        Robot robot;
            try {
                boolean capsActivo = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
                robot = new Robot();
                if(capsActivo){
                    robot.keyPress(KeyEvent.VK_CAPS_LOCK);
                    robot.keyRelease(KeyEvent.VK_CAPS_LOCK);
                }
                                
                //Alt Tab cambio de pantalla a Pagina de CUPAD
                robot.keyPress(KeyEvent.VK_ALT);
                robot.delay(100);
                robot.keyPress(KeyEvent.VK_TAB);
                robot.delay(100);
                robot.keyRelease(KeyEvent.VK_TAB);
                robot.delay(100);
                robot.keyRelease(KeyEvent.VK_ALT);
                
                robot.delay(500);

                ///Escribre Ci
                //byte user [] = registro.getUser().getBytes();
                JRobot jRobot = new JRobot();
                if(toggleButtonMail.isSelected()){
                    byte mail [] = textFieldMail.getText().getBytes();

                    for (int i = 0 ; i < mail.length ; i++) {
                   
                    jRobot.keyPressed((char)mail[i]);
                     
                    robot.delay(100);
      

                   }
                }
                if(toggleButtonUser.isSelected()){
                    byte user [] = textFieldUser.getText().getBytes();

                    for (int i = 0 ; i < user.length ; i++) {

                        jRobot.keyPressed((char)user[i]);

                        robot.delay(100);

                    }
                }
                if(toggleButtonEnter.isSelected()){
                   robot.keyPress(KeyEvent.VK_ENTER);
                   robot.keyRelease(KeyEvent.VK_ENTER); 
                   robot.delay(3000);
                }
                else{
                    if(toggleButtonMail.isSelected()||toggleButtonUser.isSelected()){
                        if(toggleButtonPassword.isSelected()){
                            robot.keyPress(KeyEvent.VK_TAB);
                            robot.keyRelease(KeyEvent.VK_TAB);
                            robot.delay(100);
                        }
                    }
                    
                }
                if(toggleButtonPassword.isSelected()){
                    
                    byte password [] = textFieldPassword.getText().getBytes();
                    for (int i = 0 ; i < password.length ; i++) {

                        jRobot.keyPressed((char)password[i]);
                        robot.delay(100);
                    }
                }
                if(toggleButtonEnter2.isSelected()){
                    robot.keyPress(KeyEvent.VK_ENTER);
                    robot.keyRelease(KeyEvent.VK_ENTER);
                }
               } 
              catch (AWTException  ex) {
               Logger.getLogger(PanelRegistro1.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_buttonIngresarActionPerformed

    public boolean isResgistro(){
        if(textFieldUrl.getText().equals("")){
            return false;
        }
        if(textFieldNombre.getText().equals("")){
            return false;
        }
        if(textFieldMail.getText().equals("")){
            return false;
        }
        if(textFieldUser.getText().equals("")){
            return false;
        }
        if(textFieldPassword.getText().equals("")){
            return false;
        }
        return true;
    }
    private void toggleButtonMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonMailActionPerformed
        // TODO add your handling code here:
        if(toggleButtonUser.isSelected()){
            toggleButtonUser.setSelected(false);
        }
    }//GEN-LAST:event_toggleButtonMailActionPerformed

    private void toggleButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonUserActionPerformed
        // TODO add your handling code here:
        if(toggleButtonMail.isSelected()){
            toggleButtonMail.setSelected(false);
        }
    }//GEN-LAST:event_toggleButtonUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacebookActionPerformed
        // TODO add your handling code here:
        textFieldUrl.setText("www.facebook.com");
        textFieldNombre.setText("FACEBOOK");
        textFieldMail.setText("escuela.schumager@gmail.com");
        textFieldUser.setText("Faacebook");
        textFieldPassword.setText("Schum319461ageran");
        
        toggleButtonMail.setSelected(true);
        toggleButtonUser.setSelected(false);
        toggleButtonEnter.setSelected(false);
        toggleButtonPassword.setSelected(true);
        toggleButtonEnter2.setSelected(true);
    }//GEN-LAST:event_buttonFacebookActionPerformed

    private void buttonGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoogleActionPerformed
        // TODO add your handling code here:
        textFieldUrl.setText("www.gmail.com");
        textFieldNombre.setText("GMAIL");
        textFieldMail.setText("escuela.schumager@gmail.com");
        textFieldUser.setText("EscuelaSchumager");
        textFieldPassword.setText("chiqui11042016lina");
        
        toggleButtonMail.setSelected(true);
        toggleButtonUser.setSelected(false);
        toggleButtonEnter.setSelected(true);
        toggleButtonPassword.setSelected(true);
        toggleButtonEnter2.setSelected(true);
    }//GEN-LAST:event_buttonGoogleActionPerformed

    private void buttonTwiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwiterActionPerformed
        // TODO add your handling code here:
        textFieldUrl.setText("www.x.com");
        textFieldNombre.setText("TWITER");
        textFieldMail.setText("escuela.schumager@gmail.com");
        textFieldUser.setText("@EscuelaSchumager");
        textFieldPassword.setText("T319461ter");
        
        toggleButtonMail.setSelected(true);
        toggleButtonUser.setSelected(false);
        toggleButtonEnter.setSelected(true);
        toggleButtonPassword.setSelected(true);
        toggleButtonEnter2.setSelected(true);

    }//GEN-LAST:event_buttonTwiterActionPerformed

    private void buttonTuCuateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTuCuateActionPerformed
        // TODO add your handling code here:
        textFieldUrl.setText("www.tucuate.com");
        textFieldNombre.setText("TU CUATE");
        textFieldMail.setText("hos.fl700@gmail.com");
        textFieldUser.setText("71247983");
        textFieldPassword.setText("Tu6572175cuate");
       
        toggleButtonMail.setSelected(false);
        toggleButtonUser.setSelected(true);
        toggleButtonEnter.setSelected(false);
        toggleButtonPassword.setSelected(true);
        toggleButtonEnter2.setSelected(true);
    }//GEN-LAST:event_buttonTuCuateActionPerformed

    private void buttonBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBrowserActionPerformed
        try {
            // TODO add your handling code here:
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + textFieldUrl.getText());

        } catch (IOException ex) {
            Logger.getLogger(PanelRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBrowserActionPerformed
    
    Registro registro; 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBrowser;
    private javax.swing.JButton buttonFacebook;
    private javax.swing.JButton buttonGoogle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonIngresar;
    private javax.swing.JButton buttonTuCuate;
    private javax.swing.JButton buttonTwiter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private com.schumager.mypassword.view.PanelNumeros panelNumeros1;
    private com.schumager.mypassword.view.table.TableRegistro tableRegistro;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldMail;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldNombre;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldPassword;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldRecuperar;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldUrl;
    private com.schumager.mypassword.view.components.TextFieldLabel textFieldUser;
    private javax.swing.JToggleButton toggleButtonEnter;
    private javax.swing.JToggleButton toggleButtonEnter2;
    private javax.swing.JToggleButton toggleButtonMail;
    private javax.swing.JToggleButton toggleButtonPassword;
    private javax.swing.JToggleButton toggleButtonUser;
    // End of variables declaration//GEN-END:variables
}
